### ISSUE TITLE
[CICD] Coopang Project 배포 과정

### ISSUE THREAD

**Issue by jiminchur** [dev-wonny/coopang#165]
## Todo
* [ ] 배포용 브랜치 하나 추가 생성하기 (#00-DEV-cicd)
* [ ] 폴더가 변경사항이 있을 경우에 따로 적용하기
* [ ] docker로 빌드를 한뒤 ec2에서 빌드한 부분만 따로 재 배포 하기

**Comment by jiminchur** [comment]
## path 설정을 통한 서버별 독립적으로 배포하기
```
name: Deploy to EC2

on:
  push:
    branches:
      - #DEV-cicd # 배포할 브랜치 설정.
    paths:
      - ./BOOT/gateway/**
      - ./BOOT/user/**
      - ./BOOT/hub/**
      - ./BOOT/delivery/**
      - ./BOOT/order/**
      - ./BOOT/product/**
      - ./CLOUD/eureka/**
      - ./BOOT/ainoti/**
jobs:
  build:
    runs-on: ubuntu-latest
```
